# Generated by Django 4.1.6 on 2023-02-06 01:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restrapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='updated_at',
            field=models.DateField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='created_at',
            field=models.DateField(auto_now_add=True),
        ),
    ]
